stages:
  stage_1:
    cmd: python stage_01.py
    deps:
    - stage_01.py
    outs:
    - artifacts01.txt
    
  stage_2:
    cmd: python stage-02.py
    deps:
    - stage-02.py
    - artifacts01.txt
   
         
    
            
      


  